# Generated by Django 6.0.3 on 2026-03-24 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_user_event_registration'),
        ),
    ]
